@startuml ModeleDonnees

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam shadowing false
skinparam roundCorner 10
skinparam class {
  BackgroundColor<<Fait>> #FFD700
  BackgroundColor<<Dimension>> #AACCFF
  BorderColor #333333
  FontSize 12
}

' ===== DIMENSIONS PARTAGÉES / HAUT =====
class DIM_MISSION << Dimension >> {
  + ID_MISSION	 : INT <<PK>>
  --
  + TYPE_MISSION : VARCHAR
  + VILLE_DEPART : VARCHAR
  + PAYS_DEPART : VARCHAR
  + VILLE_DESTINATION : VARCHAR
  + PAYS_DESTINATION : VARCHAR
  + TRANSPORT : VARCHAR
  + ALLER_RETOUR : BOOLEEN  
}

class DIM_MATERIEL << Dimension >> {
  + ID_MATERIEL : INT <<PK>>
  --
  + TYPE : VARCHAR
  + MODELE : VARCHAR
}

' ===== DIMENSION CENTRALE PARTAGÉE =====
class DIM_PERSONNEL << Dimension >> {
  + ID_PERSONNEL : INT <<PK>>
  --
  + FONCTION_PERSONNEL : VARCHAR
  + ID_SITE : VARCHAR
}

class DIM_SITE << Dimension >> {
  + ID_SITE: INT <<PK>>
}

class DIM_DATE << Dimension >> {
  + ID_DATE : DATE <<PK>>
}

' ===== TABLES DE FAITS =====
class FAIT_MISSION << Fait >> {
  + ID_PERSONNEL : INT <<FK>>
  + id_mission : INT <<FK>>
  + ID_SITE : INT <<FK>>
  + ID_DATE : DATE <<FK>>
}

class FAIT_MATERIEL << Fait >> {
  + ID_PERSONNEL : INT <<FK>>
  + ID_MATERIEL : INT <<FK>>
  + ID_SITE : INT <<FK>>
  + ID_DATE : DATE <<FK>>
}

' ===== POSITIONNEMENT =====
' Ligne du haut : dimensions spécifiques
DIM_MISSION  -[hidden]right- DIM_MATERIEL

' Faits côte à côte au milieu
FAIT_MISSION -[hidden]right- FAIT_MATERIEL

' Ligne du bas : dimensions partagées
DIM_PERSONNEL -[hidden]right- DIM_SITE

' ===== RELATIONS FAIT_MISSION =====
DIM_MISSION       "1" --> "0..*" FAIT_MISSION
DIM_PERSONNEL     "1" --> "0..*" FAIT_MISSION
DIM_SITE          "1" --> "0..*" FAIT_MISSION
DIM_DATE    "1" --> "0..*" FAIT_MISSION

' ===== RELATIONS FAIT_MATERIEL =====
DIM_MATERIEL      "1" --> "0..*" FAIT_MATERIEL
DIM_PERSONNEL     "1" --> "0..*" FAIT_MATERIEL
DIM_SITE          "1" --> "0..*" FAIT_MATERIEL
DIM_DATE  "1" --> "0..*" FAIT_MATERIEL



@enduml